"""
Raja Banks Trading Agent - Strategy Engine
S/R pipeline, 3 entry types (C1/C0, Impulse, Break & Retest),
pre-entry filters, fakeout detection.
"""
import logging
import uuid
import numpy as np
import pandas as pd
from typing import Optional, List, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime, timezone

from config import StrategyConfig
from constants import (
    EntryType, TradeDirection, TrendType, SessionType,
    VolumeLevel, ZoneType
)
from market_analyzer import MarketState, SRLevel, MarketAnalyzer
from utils import (
    price_to_pips, pips_to_price, body_ratio, is_bullish, is_bearish,
    classify_wick, is_wickless, candle_volume_strength,
    get_body_top, get_body_bottom, is_high_volume_session,
    is_tradeable_session
)

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by the strategy."""
    trade_id: str
    direction: TradeDirection
    entry_type: EntryType
    entry_price: float
    sl_price: float
    tp1_price: float
    tp2_price: float
    risk_pips: float
    sr_level: SRLevel
    confidence: float = 1.0
    context: Dict[str, Any] = field(default_factory=dict)

    @property
    def rr_tp1(self) -> float:
        if self.risk_pips <= 0:
            return 0
        tp1_dist = price_to_pips(abs(self.tp1_price - self.entry_price))
        return tp1_dist / self.risk_pips

    @property
    def rr_tp2(self) -> float:
        if self.risk_pips <= 0:
            return 0
        tp2_dist = price_to_pips(abs(self.tp2_price - self.entry_price))
        return tp2_dist / self.risk_pips


@dataclass
class PendingC0:
    """Pending order waiting for C0 confirmation after C1 rejection."""
    c1_bar_index: int
    direction: TradeDirection
    entry_price: float  # C1 extreme (pending stop)
    sl_price: float  # C1 wick extreme (opposite side)
    sr_level: SRLevel
    bars_waiting: int = 0
    context: Dict[str, Any] = field(default_factory=dict)


class Strategy:
    """
    Raja Banks Market Fluidity Strategy implementation.

    Entry Types:
    1. C1/C0 Rejection - Primary entry at S/R zones
    2. Impulse - Trending markets with volume confirmation
    3. Break & Retest - 80% rule after S/R break
    """

    def __init__(self, config: StrategyConfig, analyzer: MarketAnalyzer):
        self.cfg = config
        self.analyzer = analyzer
        self.pending_orders: List[PendingC0] = []

    def generate_signals(self, df: pd.DataFrame,
                         market: MarketState,
                         blocked_patterns: List[str] = None
                         ) -> List[Signal]:
        """
        Main signal generation pipeline.
        Returns list of valid signals (usually 0-1 per bar).
        """
        if df.empty or len(df) < 10:
            return []

        signals = []
        blocked = blocked_patterns or []

        # Check session filter
        utc_hour = df.index[-1].hour if hasattr(df.index[-1], 'hour') else 12
        if not is_tradeable_session(utc_hour, self.cfg.session_start,
                                    self.cfg.session_end):
            logger.debug("Outside trading session, skipping signals")
            self._expire_pending_orders()
            return []

        # Session blackout (skip NY overlap whipsaw zone)
        blackout_start = getattr(self.cfg, 'session_blackout_start', 0)
        blackout_end = getattr(self.cfg, 'session_blackout_end', 0)
        if blackout_start and blackout_end and blackout_start <= utc_hour < blackout_end:
            logger.debug("Session blackout (NY overlap), skipping signals")
            return []

        # Current bar data
        bar = df.iloc[-1]
        prev_bar = df.iloc[-2] if len(df) >= 2 else bar

        # 1. Check pending C0 orders first
        c0_signals = self._check_pending_c0(bar, df, market)
        signals.extend(c0_signals)

        # 2. Scan for new C1 rejection setups
        c1_signals = self._scan_c1_rejection(bar, df, market)
        # C1 creates pending orders, not immediate signals

        # 3. Impulse entry (if enabled)
        if self.cfg.impulse_enabled:
            imp_signal = self._scan_impulse(bar, prev_bar, df, market)
            if imp_signal:
                signals.append(imp_signal)

        # 4. Break & Retest (if enabled)
        if self.cfg.break_retest_enabled:
            br_signal = self._scan_break_retest(bar, df, market)
            if br_signal:
                signals.append(br_signal)

        # Inject trend into all signal contexts
        for sig in signals:
            sig.context["trend"] = market.trend.value
            sig.context["session"] = market.session.value

        # Apply pre-entry filters and fakeout detection
        filtered = []
        for sig in signals:
            if self._passes_pre_entry_filters(sig, market, df):
                if not self._is_fakeout(sig, bar, df, market):
                    filtered.append(sig)
                else:
                    logger.info("Signal rejected: fakeout detected for %s at %.2f",
                                sig.entry_type.value, sig.entry_price)
            else:
                logger.info("Signal rejected: failed pre-entry filters for %s",
                            sig.entry_type.value)

        return filtered

    # === ENTRY TYPE 1: C1/C0 REJECTION ===

    def _scan_c1_rejection(self, bar: pd.Series, df: pd.DataFrame,
                           market: MarketState):
        """
        Scan for C1 rejection candle at S/R zone.
        C1 = candle that rejects off S/R with wick into zone and body closing away.
        If valid, creates a pending C0 order.
        """
        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        br = body_ratio(o, c, h, l)
        if br < self.cfg.c1_body_min:
            logger.debug("C1 scan: body_ratio %.2f < min %.2f, skip", br, self.cfg.c1_body_min)
            return  # Not enough body

        c1_range_pips = price_to_pips(h - l)
        if c1_range_pips < self.cfg.c1_min_range_pips:
            logger.debug("C1 scan: range %.1f pips < min %.1f, skip", c1_range_pips, self.cfg.c1_min_range_pips)
            return  # Candle too small

        logger.info("C1 candidate: O=%.2f H=%.2f L=%.2f C=%.2f | body=%.2f range=%.1f pips | %s",
                     o, h, l, c, br, c1_range_pips, "BULL" if is_bullish(o, c) else "BEAR")

        tol = self.cfg.rejection_tolerance

        # Check against support levels (bullish rejection) — asymmetric tolerance
        # Wick must dip INTO the support zone: C1_low within [level - tol*2, level + tol]
        # Body must close above level (rejection = bullish close away from zone)
        if is_bullish(o, c):
            logger.info("C1 scan: checking %d support levels (tol=$%.1f)", len(market.support_levels), tol)
            for level in sorted(market.support_levels, key=lambda x: x.price, reverse=True):
                wick_ok = l <= level.price + tol and l >= level.price - tol * 2
                logger.debug("  SUP $%.2f: low=$%.2f, range=[%.2f, %.2f], wick_ok=%s",
                             level.price, l, level.price - tol * 2, level.price + tol, wick_ok)
                if wick_ok:
                    body_bottom = min(o, c)
                    body_ok = body_bottom > level.price - tol * 0.5
                    logger.info("  SUP $%.2f: wick IN zone! body_bottom=$%.2f, need>$%.2f, body_ok=%s",
                                level.price, body_bottom, level.price - tol * 0.5, body_ok)
                    if body_ok:
                        entry = h  # Pending buy stop above C1 high
                        sl = l  # SL at C1 low (no buffer — matches backtest)

                        pending = PendingC0(
                            c1_bar_index=len(df) - 1,
                            direction=TradeDirection.BUY,
                            entry_price=entry,
                            sl_price=sl,
                            sr_level=level,
                            context={
                                "c1_body_ratio": br,
                                "c1_range_pips": c1_range_pips,
                                "c1_open": o, "c1_high": h,
                                "c1_low": l, "c1_close": c,
                                "c1_is_wickless": is_wickless(o, c, h, l),
                            }
                        )
                        self.pending_orders.append(pending)
                        logger.info("C1 bullish rejection at support %.2f, pending buy stop at %.2f",
                                    level.price, entry)
                        break  # Only take first matching level (nearest)

        # Check against resistance levels (bearish rejection) — asymmetric tolerance
        # Wick must poke INTO resistance zone: C1_high within [level - tol, level + tol*2]
        # Body must close below level (rejection = bearish close away from zone)
        if is_bearish(o, c):
            logger.info("C1 scan: checking %d resistance levels (tol=$%.1f)", len(market.resistance_levels), tol)
            for level in sorted(market.resistance_levels, key=lambda x: x.price):
                wick_ok = h >= level.price - tol and h <= level.price + tol * 2
                logger.debug("  RES $%.2f: high=$%.2f, range=[%.2f, %.2f], wick_ok=%s",
                             level.price, h, level.price - tol, level.price + tol * 2, wick_ok)
                if wick_ok:
                    body_top = max(o, c)
                    body_ok = body_top < level.price + tol * 0.5
                    logger.info("  RES $%.2f: wick IN zone! body_top=$%.2f, need<$%.2f, body_ok=%s",
                                level.price, body_top, level.price + tol * 0.5, body_ok)
                    if body_ok:
                        entry = l  # Pending sell stop below C1 low
                        sl = h  # SL at C1 high (no buffer — matches backtest)

                        pending = PendingC0(
                            c1_bar_index=len(df) - 1,
                            direction=TradeDirection.SELL,
                            entry_price=entry,
                            sl_price=sl,
                            sr_level=level,
                            context={
                                "c1_body_ratio": br,
                                "c1_range_pips": c1_range_pips,
                                "c1_open": o, "c1_high": h,
                                "c1_low": l, "c1_close": c,
                                "c1_is_wickless": is_wickless(o, c, h, l),
                            }
                        )
                        self.pending_orders.append(pending)
                        logger.info("C1 bearish rejection at resistance %.2f, pending sell stop at %.2f",
                                    level.price, entry)
                        break  # Only take first matching level (nearest)

    def _check_pending_c0(self, bar: pd.Series, df: pd.DataFrame,
                          market: MarketState) -> List[Signal]:
        """
        Check if current bar triggers any pending C0 orders.
        C0 = the confirmation candle that triggers the pending stop.
        """
        signals = []
        still_pending = []

        for pending in self.pending_orders:
            pending.bars_waiting += 1

            # Expire if too many bars
            if pending.bars_waiting > self.cfg.pending_expiry_bars:
                logger.debug("Pending C0 expired after %d bars",
                             pending.bars_waiting)
                continue

            triggered = False
            if pending.direction == TradeDirection.BUY:
                # Buy stop: triggered if bar's high >= entry price
                if float(bar["High"]) >= pending.entry_price:
                    triggered = True
            else:
                # Sell stop: triggered if bar's low <= entry price
                if float(bar["Low"]) <= pending.entry_price:
                    triggered = True

            if triggered:
                risk_pips = price_to_pips(
                    abs(pending.entry_price - pending.sl_price)
                )

                # Calculate TP levels
                tp1, tp2 = self._calculate_tp(
                    pending.direction, pending.entry_price,
                    risk_pips, market
                )

                signal = Signal(
                    trade_id=f"C1C0-{uuid.uuid4().hex[:8]}",
                    direction=pending.direction,
                    entry_type=EntryType.C1_C0_REJECTION,
                    entry_price=pending.entry_price,
                    sl_price=pending.sl_price,
                    tp1_price=tp1,
                    tp2_price=tp2,
                    risk_pips=risk_pips,
                    sr_level=pending.sr_level,
                    context=pending.context,
                )
                signals.append(signal)
                logger.info("C0 triggered! %s at %.2f, SL %.2f, TP1 %.2f",
                            pending.direction.value, pending.entry_price,
                            pending.sl_price, tp1)
            else:
                still_pending.append(pending)

        self.pending_orders = still_pending
        return signals

    # === ENTRY TYPE 2: IMPULSE ===

    def _scan_impulse(self, bar: pd.Series, prev_bar: pd.Series,
                      df: pd.DataFrame, market: MarketState
                      ) -> Optional[Signal]:
        """
        Impulse entry: strong body candle in trending market with volume.
        - Trend must be established (HH/HL or LL/LH)
        - Body ratio >= impulse_min_body_ratio
        - Volume > SMA(20) * multiplier
        - Clean range to the left (no congestion)
        """
        if market.trend == TrendType.CONSOLIDATION:
            logger.debug("Impulse scan: skipping — market in consolidation")
            return None

        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        br = body_ratio(o, c, h, l)
        if br < self.cfg.impulse_min_body_ratio:
            logger.debug("Impulse scan: body_ratio %.2f < min %.2f", br, self.cfg.impulse_min_body_ratio)
            return None

        # Volume check — skip filter when no real volume data (common for gold on TwelveData)
        if "Volume" in df.columns:
            vol = float(bar["Volume"])
            vol_sma = float(df["Volume"].tail(20).mean())
            if vol_sma > 0 and vol > 0 and vol < vol_sma * self.cfg.impulse_volume_multiplier:
                logger.debug("Impulse scan: volume %.0f < SMA*%.1f (%.0f)", vol, self.cfg.impulse_volume_multiplier, vol_sma * self.cfg.impulse_volume_multiplier)
                return None
            vol_ratio = vol / vol_sma if vol_sma > 0 else 1.0
        else:
            vol_ratio = 1.0

        # Clean range check (no congestion to the left)
        lookback = min(self.cfg.impulse_clean_range_lookback, len(df) - 1)
        if not self._has_clean_range(df, lookback, "BUY" if is_bullish(o, c) else "SELL"):
            return None

        # Direction must align with trend
        if market.trend == TrendType.UPTREND and not is_bullish(o, c):
            return None
        if market.trend == TrendType.DOWNTREND and not is_bearish(o, c):
            return None

        # Find nearest S/R for context
        if is_bullish(o, c):
            direction = TradeDirection.BUY
            entry = c  # Enter at close of impulse candle
            sl = l - pips_to_price(5)  # Below impulse candle low
            sr = self.analyzer.get_nearest_support(
                market.support_levels, entry
            )
        else:
            direction = TradeDirection.SELL
            entry = c
            sl = h + pips_to_price(5)
            sr = self.analyzer.get_nearest_resistance(
                market.resistance_levels, entry
            )

        if sr is None:
            # Create a synthetic level
            sr = SRLevel(price=sl, zone_type=ZoneType.SUPPORT if direction == TradeDirection.BUY else ZoneType.RESISTANCE)

        risk_pips = price_to_pips(abs(entry - sl))
        tp1, tp2 = self._calculate_tp(direction, entry, risk_pips, market)

        return Signal(
            trade_id=f"IMP-{uuid.uuid4().hex[:8]}",
            direction=direction,
            entry_type=EntryType.IMPULSE,
            entry_price=entry,
            sl_price=sl,
            tp1_price=tp1,
            tp2_price=tp2,
            risk_pips=risk_pips,
            sr_level=sr,
            context={
                "impulse_body_ratio": br,
                "impulse_volume_ratio": vol_ratio,
                "clean_range_bars": lookback,
                "trend": market.trend.value,
            }
        )

    def _has_clean_range(self, df: pd.DataFrame, lookback: int,
                         direction: str) -> bool:
        """Check if price has clean range (no congestion) to the left."""
        if lookback <= 0 or len(df) < lookback + 1:
            return True

        recent = df.tail(lookback + 1)
        current = recent.iloc[-1]

        if direction == "BUY":
            # For buys, check that current high is above all recent highs
            prev_highs = recent["High"].iloc[:-1]
            return float(current["High"]) > float(prev_highs.max())
        else:
            prev_lows = recent["Low"].iloc[:-1]
            return float(current["Low"]) < float(prev_lows.min())

    # === ENTRY TYPE 3: BREAK & RETEST ===

    def _scan_break_retest(self, bar: pd.Series, df: pd.DataFrame,
                           market: MarketState) -> Optional[Signal]:
        """
        Break & Retest entry (Raja's 80% rule):
        1. Price breaks through S/R level
        2. Pulls back to retest the broken level (now flipped)
        3. C1/C0 rejection at the flipped zone
        """
        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        break_conf_price = pips_to_price(self.cfg.break_confirmation_pips)

        # Check for support break -> becomes resistance (sell setup)
        for level in market.support_levels:
            # Check if recent bars broke below this support
            recent_bars = df.tail(self.cfg.retest_max_bars)
            broke_below = any(
                float(recent_bars["Close"].iloc[i]) < level.price - break_conf_price
                for i in range(max(0, len(recent_bars) - self.cfg.retest_max_bars),
                               len(recent_bars) - 1)
            )

            if broke_below:
                # Now check if current bar is retesting from below
                if abs(h - level.price) <= self.cfg.rejection_tolerance:
                    if is_bearish(o, c):
                        # Bearish rejection at broken support (now resistance)
                        entry = l
                        sl = h + pips_to_price(1)
                        risk_pips = price_to_pips(abs(entry - sl))
                        tp1, tp2 = self._calculate_tp(
                            TradeDirection.SELL, entry, risk_pips, market
                        )

                        flipped = SRLevel(
                            price=level.price,
                            zone_type=ZoneType.RESISTANCE,
                            touches=level.touches,
                            htf_aligned=level.htf_aligned,
                            strength=level.strength,
                        )

                        return Signal(
                            trade_id=f"BR-{uuid.uuid4().hex[:8]}",
                            direction=TradeDirection.SELL,
                            entry_type=EntryType.BREAK_RETEST,
                            entry_price=entry,
                            sl_price=sl,
                            tp1_price=tp1,
                            tp2_price=tp2,
                            risk_pips=risk_pips,
                            sr_level=flipped,
                            context={
                                "break_level_price": level.price,
                                "retest_bars_waited": self.cfg.retest_max_bars,
                                "original_zone_type": "support",
                            }
                        )

        # Check for resistance break -> becomes support (buy setup)
        for level in market.resistance_levels:
            recent_bars = df.tail(self.cfg.retest_max_bars)
            broke_above = any(
                float(recent_bars["Close"].iloc[i]) > level.price + break_conf_price
                for i in range(max(0, len(recent_bars) - self.cfg.retest_max_bars),
                               len(recent_bars) - 1)
            )

            if broke_above:
                if abs(l - level.price) <= self.cfg.rejection_tolerance:
                    if is_bullish(o, c):
                        entry = h
                        sl = l - pips_to_price(1)
                        risk_pips = price_to_pips(abs(entry - sl))
                        tp1, tp2 = self._calculate_tp(
                            TradeDirection.BUY, entry, risk_pips, market
                        )

                        flipped = SRLevel(
                            price=level.price,
                            zone_type=ZoneType.SUPPORT,
                            touches=level.touches,
                            htf_aligned=level.htf_aligned,
                            strength=level.strength,
                        )

                        return Signal(
                            trade_id=f"BR-{uuid.uuid4().hex[:8]}",
                            direction=TradeDirection.BUY,
                            entry_type=EntryType.BREAK_RETEST,
                            entry_price=entry,
                            sl_price=sl,
                            tp1_price=tp1,
                            tp2_price=tp2,
                            risk_pips=risk_pips,
                            sr_level=flipped,
                            context={
                                "break_level_price": level.price,
                                "retest_bars_waited": self.cfg.retest_max_bars,
                                "original_zone_type": "resistance",
                            }
                        )

        return None

    # === PRE-ENTRY FILTERS ===

    def _passes_pre_entry_filters(self, signal: Signal,
                                  market: MarketState,
                                  df: pd.DataFrame) -> bool:
        """
        Raja's pre-entry checklist:
        1. Minimum room to opposing S/R (min_room_pips)
        2. Not in mid-range (max_mid_range_pct)
        3. SL within bounds (min_sl_pips, max_risk_pips)
        4. Spread check
        """
        # 1. Room to opposing S/R
        room = self.analyzer.get_room_to_opposing(
            signal.direction.value, signal.entry_price,
            market.support_levels, market.resistance_levels
        )
        if room < self.cfg.min_room_pips:
            logger.info("Pre-filter REJECT: room %.1f pips < min %.1f (entry=%.2f, %s)",
                        room, self.cfg.min_room_pips, signal.entry_price, signal.direction.value)
            return False

        # 2. Mid-range check
        if market.support_levels and market.resistance_levels:
            nearest_sup = max(l.price for l in market.support_levels)
            nearest_res = min(l.price for l in market.resistance_levels)
            total_range = nearest_res - nearest_sup
            if total_range > 0:
                position = (signal.entry_price - nearest_sup) / total_range
                mid_low = 0.5 - self.cfg.max_mid_range_pct / 2
                mid_high = 0.5 + self.cfg.max_mid_range_pct / 2
                if mid_low < position < mid_high:
                    logger.debug("Rejected: mid-range position %.2f", position)
                    return False

        # 3. SL bounds - reject signals outside range (no padding)
        if signal.risk_pips < self.cfg.min_sl_pips:
            logger.debug("Rejected: SL too tight %.1f pips (need large C1 for conviction)", signal.risk_pips)
            return False
        if signal.risk_pips > self.cfg.max_risk_pips:
            logger.debug("Rejected: SL too wide %.1f pips", signal.risk_pips)
            return False

        # 4. HTF alignment bonus (soft filter) — channel method already
        # selects strong zones, so we only reject truly weak channels
        # with no HTF alignment AND very low strength score
        if not signal.sr_level.htf_aligned and signal.sr_level.strength < 10:
            logger.info("Pre-filter REJECT: S/R channel too weak (strength=%.1f, no HTF)",
                         signal.sr_level.strength)
            return False

        logger.info("Pre-filter PASSED: room=%.1f, risk=%.1f pips, sr_str=%.1f, htf=%s",
                     room, signal.risk_pips, signal.sr_level.strength, signal.sr_level.htf_aligned)

        return True

    # === FAKEOUT DETECTION ===

    def _is_fakeout(self, signal: Signal, bar: pd.Series,
                    df: pd.DataFrame, market: MarketState) -> bool:
        """
        Detect potential fakeout signals:
        - Very weak body (< 0.15 body ratio) = doji/indecision
        - Low volume impulse (only when real volume data exists)
        - Counter-trend without strong body AND low volume session
        """
        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        br = body_ratio(o, c, h, l)

        # Very weak body = doji/indecision candle (loosened from 0.20 to 0.15)
        if br < 0.15:
            logger.debug("Fakeout: doji/indecision body ratio %.2f", br)
            return True

        # Low volume fakeout — only check when real volume data exists
        # (TwelveData often returns 0 volume for gold, so skip in that case)
        if market.current_volume_level == VolumeLevel.LOW:
            avg_vol = float(df["Volume"].tail(20).mean()) if "Volume" in df.columns else 0
            if avg_vol > 0:  # Only filter when we have real volume data
                if signal.entry_type == EntryType.IMPULSE:
                    logger.debug("Fakeout: impulse with confirmed low volume")
                    return True

        # Counter-trend without strong body: need body_ratio >= 0.35 (loosened from 0.40)
        if signal.direction == TradeDirection.BUY and market.trend == TrendType.DOWNTREND:
            if br < 0.35 and not is_high_volume_session(market.session):
                logger.debug("Fakeout: counter-trend buy without conviction (br=%.2f)", br)
                return True
        if signal.direction == TradeDirection.SELL and market.trend == TrendType.UPTREND:
            if br < 0.35 and not is_high_volume_session(market.session):
                logger.debug("Fakeout: counter-trend sell without conviction (br=%.2f)", br)
                return True

        return False

    # === TP CALCULATION ===

    def _calculate_tp(self, direction: TradeDirection, entry: float,
                      risk_pips: float, market: MarketState
                      ) -> tuple:
        """
        Calculate TP1 and TP2 prices.
        TP1 = 1:1 R:R
        TP2 = nearest opposing S/R or max 2.5R
        """
        risk_dollars = pips_to_price(risk_pips)
        tp1_dollars = risk_dollars * self.cfg.tp1_rr

        if direction == TradeDirection.BUY:
            tp1 = entry + tp1_dollars
            # TP2: nearest resistance or max RR
            tp2_max = entry + risk_dollars * self.cfg.tp2_max_rr
            nearest_res = self.analyzer.get_nearest_resistance(
                market.resistance_levels, entry
            )
            if nearest_res and nearest_res.price < tp2_max:
                tp2 = nearest_res.price
            else:
                tp2 = tp2_max
        else:
            tp1 = entry - tp1_dollars
            tp2_max = entry - risk_dollars * self.cfg.tp2_max_rr
            nearest_sup = self.analyzer.get_nearest_support(
                market.support_levels, entry
            )
            if nearest_sup and nearest_sup.price > tp2_max:
                tp2 = nearest_sup.price
            else:
                tp2 = tp2_max

        return round(tp1, 2), round(tp2, 2)

    def _expire_pending_orders(self):
        """Expire all pending orders (called outside trading hours)."""
        if self.pending_orders:
            logger.info("Expiring %d pending orders (outside session)",
                        len(self.pending_orders))
            self.pending_orders.clear()
