"""
Raja Banks Trading Agent - Strategy Engine
S/R pipeline, 3 entry types (C1/C0, Impulse, Break & Retest),
pre-entry filters, fakeout detection.
"""
import logging
import uuid
import numpy as np
import pandas as pd
from typing import Optional, List, Dict, Any
from dataclasses import dataclass, field
from datetime import datetime, timezone

from config import StrategyConfig
from constants import (
    EntryType, TradeDirection, TrendType, SessionType,
    VolumeLevel, ZoneType
)
from market_analyzer import MarketState, SRLevel, MarketAnalyzer
from utils import (
    price_to_pips, pips_to_price, body_ratio, is_bullish, is_bearish,
    classify_wick, is_wickless, candle_volume_strength,
    get_body_top, get_body_bottom, is_high_volume_session,
    is_tradeable_session
)

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """Trading signal generated by the strategy."""
    trade_id: str
    direction: TradeDirection
    entry_type: EntryType
    entry_price: float
    sl_price: float
    tp1_price: float
    tp2_price: float
    risk_pips: float
    sr_level: SRLevel
    confidence: float = 1.0
    context: Dict[str, Any] = field(default_factory=dict)

    @property
    def rr_tp1(self) -> float:
        if self.risk_pips <= 0:
            return 0
        tp1_dist = price_to_pips(abs(self.tp1_price - self.entry_price))
        return tp1_dist / self.risk_pips

    @property
    def rr_tp2(self) -> float:
        if self.risk_pips <= 0:
            return 0
        tp2_dist = price_to_pips(abs(self.tp2_price - self.entry_price))
        return tp2_dist / self.risk_pips


# NOTE: PendingC0 dataclass removed — the two-bar strategy queue has been replaced
# with direct Signal generation on C1 close. MT5 pending_stop_orders (main.py) is now
# the single source of truth for pending state. Structural invalidation runs every tick.


class Strategy:
    """
    Raja Banks Market Fluidity Strategy implementation.

    Entry Types:
    1. C1/C0 Rejection - Primary entry at S/R zones
    2. Impulse - Trending markets with volume confirmation
    3. Break & Retest - 80% rule after S/R break
    """

    def __init__(self, config: StrategyConfig, analyzer: MarketAnalyzer):
        self.cfg = config
        self.analyzer = analyzer
        # Kept for compatibility with any external referencer (e.g. logs).
        # Strategy no longer queues pending C0 — MT5 holds the pending stop directly.
        self.pending_orders: list = []

    def generate_signals(self, df: pd.DataFrame,
                         market: MarketState,
                         blocked_patterns: List[str] = None
                         ) -> List[Signal]:
        """
        Main signal generation pipeline.
        Returns list of valid signals (usually 0-1 per bar).

        CRITICAL — COMPLETED BAR RULE (live trading fix):
        C1 and C0 detection use df.iloc[-2] (the last COMPLETED bar),
        NOT df.iloc[-1] (the forming bar whose OHLC is still changing).
        This matches backtest behavior where every bar is fully formed.
        Without this, C1 entry/SL levels are wrong (based on incomplete
        candle) and C0 direction checks are meaningless (bar not closed).
        """
        if df.empty or len(df) < 20:
            return []

        signals = []
        blocked = blocked_patterns or []

        # Use wall-clock UTC for session checks, not bar timestamp hour.
        # ICMarkets bar timestamps are EET (UTC+3) — df.index[-1].hour
        # gives EET, shifting the session window 3 hours early.
        utc_hour = datetime.now(timezone.utc).hour
        if not is_tradeable_session(utc_hour, self.cfg.session_start,
                                    self.cfg.session_end):
            logger.debug("Outside trading session, skipping signals")
            self._expire_pending_orders()
            return []

        # Session blackout (skip NY overlap whipsaw zone 11:00-14:00 UTC)
        blackout_start = getattr(self.cfg, 'session_blackout_start', 0)
        blackout_end = getattr(self.cfg, 'session_blackout_end', 0)
        if blackout_start and blackout_end and blackout_start <= utc_hour < blackout_end:
            logger.debug("Session blackout (NY overlap), skipping signals")
            # 📵 KILL SWITCH — expire pending C1 orders at blackout entry.
            # During the 3-hour blackout, _check_pending_c0 is never called so
            # bars_waiting never increments. A C1 from 10:59 UTC would still have
            # bars_waiting=0 at 14:00 UTC and fire on a 3-hour-stale bar as C0.
            # The pending_expiry_bars=3 rule (45 min) can't enforce itself if the
            # counter never ticks. Expire all pending at blackout entry instead.
            self._expire_pending_orders()
            return []

        # === COMPLETED BAR — the last fully closed candle ===
        # df.iloc[-1] = forming bar (OHLC still changing — DO NOT use for C1/C0)
        # df.iloc[-2] = last completed bar (final OHLC — use for all entry logic)
        completed_bar = df.iloc[-2]
        prev_completed = df.iloc[-3] if len(df) >= 3 else completed_bar

        # 1. Scan for C1 rejection — builds direct stop-order Signals (no 2-bar wait)
        c1_signals = self._scan_c1_rejection(completed_bar, df, market)
        signals.extend(c1_signals)

        # 3. Impulse entry (if enabled) — also on completed bar
        if self.cfg.impulse_enabled:
            imp_signal = self._scan_impulse(completed_bar, prev_completed, df, market)
            if imp_signal:
                signals.append(imp_signal)

        # 4. Break & Retest (if enabled) — also on completed bar
        if self.cfg.break_retest_enabled:
            br_signal = self._scan_break_retest(completed_bar, df, market)
            if br_signal:
                signals.append(br_signal)

        # Inject trend into all signal contexts
        for sig in signals:
            sig.context["trend"] = market.trend.value
            sig.context["session"] = market.session.value

        # Apply pre-entry filters and fakeout detection (using completed bar)
        filtered = []
        for sig in signals:
            if self._passes_pre_entry_filters(sig, market, df):
                if not self._is_fakeout(sig, completed_bar, df, market):
                    filtered.append(sig)
                else:
                    logger.info("Signal rejected: fakeout detected for %s at %.2f",
                                sig.entry_type.value, sig.entry_price)
            else:
                logger.info("Signal rejected: failed pre-entry filters for %s",
                            sig.entry_type.value)

        return filtered

    # === ENTRY TYPE 1: C1/C0 REJECTION ===

    def _scan_c1_rejection(self, bar: pd.Series, df: pd.DataFrame,
                           market: MarketState) -> List[Signal]:
        """
        Scan for C1 rejection candle at S/R zone and emit a stop-order Signal
        immediately on C1 close.

        🔴 NEW TIMING MODEL (Raja original): C1 closes → Signal with is_stop_order=True
        built right here → main.py places MT5 BUY_STOP/SELL_STOP within the same tick.
        The next forming candle (C0) either triggers the fill, breaches C1 wick
        (structural invalidation in main.py), or times out (_expire_pending_stops).

        No more strategy-level queue. No more C0 close-based gate validation.

        CRITICAL: `bar` must be the last COMPLETED bar (df.iloc[-2]), NOT the forming bar.
        """
        signals: List[Signal] = []

        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        br = body_ratio(o, c, h, l)
        if br < self.cfg.c1_body_min:
            logger.debug("C1 scan: body_ratio %.2f < min %.2f, skip", br, self.cfg.c1_body_min)
            return signals  # Not enough body

        c1_range_pips = price_to_pips(h - l)
        if c1_range_pips < self.cfg.c1_min_range_pips:
            logger.debug("C1 scan: range %.1f pips < min %.1f, skip",
                         c1_range_pips, self.cfg.c1_min_range_pips)
            return signals  # Candle too small

        logger.info("C1 candidate: O=%.2f H=%.2f L=%.2f C=%.2f | body=%.2f range=%.1f pips | %s",
                     o, h, l, c, br, c1_range_pips, "BULL" if is_bullish(o, c) else "BEAR")

        tol = self.cfg.rejection_tolerance
        buffer_price = pips_to_price(self.cfg.c1_stop_buffer_pips)

        # Per-bar dedup: one signal per (zone, direction). main.py's
        # pending_stop_orders dict prevents duplicates across bars (once an MT5
        # pending for a zone is live, a subsequent C1 will land via place_stop_order
        # as a new ticket — rely on reconciler + expiry for overlap cleanup).
        seen_zones = set()

        # === BULLISH C1 → check against SUPPORT levels ===
        # Wick must dip INTO the support zone: C1_low within [level - tol, level + tol]
        # Body must close above level (rejection = bullish close away from zone).
        if is_bullish(o, c):
            logger.info("C1 scan: checking %d support levels (tol=$%.1f)",
                        len(market.support_levels), tol)
            for level in sorted(market.support_levels, key=lambda x: x.price, reverse=True):
                wick_ok = l <= level.price + tol and l >= level.price - tol
                logger.debug("  SUP $%.2f: low=$%.2f, range=[%.2f, %.2f], wick_ok=%s",
                             level.price, l, level.price - tol, level.price + tol, wick_ok)
                if not wick_ok:
                    continue

                body_bottom = min(o, c)
                body_ok = body_bottom >= level.price - tol * 0.15
                logger.info("  SUP $%.2f: wick IN zone! body_bottom=$%.2f, need>=$%.2f (close-away), body_ok=%s",
                            level.price, body_bottom, level.price - tol * 0.15, body_ok)
                if not body_ok:
                    continue

                zone_key = (level.price, TradeDirection.BUY)
                if zone_key in seen_zones:
                    break
                seen_zones.add(zone_key)

                # 🔴 Stop order = C1 high + buffer (break of rejection). SL = C1 low.
                stop_entry = h + buffer_price
                stop_sl    = l
                risk_pips  = price_to_pips(stop_entry - stop_sl)
                tp1, tp2 = self._calculate_tp(TradeDirection.BUY, stop_entry,
                                              risk_pips, market)

                signal = Signal(
                    trade_id=f"C1STOP-{uuid.uuid4().hex[:8]}",
                    direction=TradeDirection.BUY,
                    entry_type=EntryType.C1_C0_REJECTION,
                    entry_price=stop_entry,
                    sl_price=stop_sl,
                    tp1_price=tp1,
                    tp2_price=tp2,
                    risk_pips=risk_pips,
                    sr_level=level,
                    context={
                        "c1_body_ratio":     br,
                        "c1_range_pips":     c1_range_pips,
                        "c1_open":  o, "c1_high": h, "c1_low": l, "c1_close": c,
                        "c1_is_wickless":    is_wickless(o, c, h, l),
                        "c1_bar_time":       bar.name,
                        "is_stop_order":     True,    # routes to place_stop_order
                        "stop_buffer_pips":  self.cfg.c1_stop_buffer_pips,
                        "stop_expiry_bars":  self.cfg.pending_expiry_bars,
                        "invalidation_price": stop_sl,  # 🔴 tick below C1_low = setup dead
                    },
                )
                signals.append(signal)
                logger.info(
                    "C1 bullish → BUY_STOP %.2f SL %.2f risk %.1fp (zone %.2f)",
                    stop_entry, stop_sl, risk_pips, level.price
                )
                break  # Only take nearest matching level

        # === BEARISH C1 → check against RESISTANCE levels ===
        # Wick must poke INTO resistance zone: C1_high within [level - tol, level + tol]
        # Body must close below level (rejection = bearish close away from zone).
        if is_bearish(o, c):
            logger.info("C1 scan: checking %d resistance levels (tol=$%.1f)",
                        len(market.resistance_levels), tol)
            for level in sorted(market.resistance_levels, key=lambda x: x.price):
                wick_ok = h >= level.price - tol and h <= level.price + tol
                logger.debug("  RES $%.2f: high=$%.2f, range=[%.2f, %.2f], wick_ok=%s",
                             level.price, h, level.price - tol, level.price + tol, wick_ok)
                if not wick_ok:
                    continue

                body_top = max(o, c)
                body_ok = body_top <= level.price + tol * 0.15
                logger.info("  RES $%.2f: wick IN zone! body_top=$%.2f, need<=$%.2f (close-away), body_ok=%s",
                            level.price, body_top, level.price + tol * 0.15, body_ok)
                if not body_ok:
                    continue

                zone_key = (level.price, TradeDirection.SELL)
                if zone_key in seen_zones:
                    break
                seen_zones.add(zone_key)

                # 🔴 Stop order = C1 low - buffer (break of rejection). SL = C1 high.
                stop_entry = l - buffer_price
                stop_sl    = h
                risk_pips  = price_to_pips(stop_sl - stop_entry)
                tp1, tp2 = self._calculate_tp(TradeDirection.SELL, stop_entry,
                                              risk_pips, market)

                signal = Signal(
                    trade_id=f"C1STOP-{uuid.uuid4().hex[:8]}",
                    direction=TradeDirection.SELL,
                    entry_type=EntryType.C1_C0_REJECTION,
                    entry_price=stop_entry,
                    sl_price=stop_sl,
                    tp1_price=tp1,
                    tp2_price=tp2,
                    risk_pips=risk_pips,
                    sr_level=level,
                    context={
                        "c1_body_ratio":     br,
                        "c1_range_pips":     c1_range_pips,
                        "c1_open":  o, "c1_high": h, "c1_low": l, "c1_close": c,
                        "c1_is_wickless":    is_wickless(o, c, h, l),
                        "c1_bar_time":       bar.name,
                        "is_stop_order":     True,
                        "stop_buffer_pips":  self.cfg.c1_stop_buffer_pips,
                        "stop_expiry_bars":  self.cfg.pending_expiry_bars,
                        "invalidation_price": stop_sl,  # 🔴 tick above C1_high = setup dead
                    },
                )
                signals.append(signal)
                logger.info(
                    "C1 bearish → SELL_STOP %.2f SL %.2f risk %.1fp (zone %.2f)",
                    stop_entry, stop_sl, risk_pips, level.price
                )
                break

        return signals

    # NOTE: _check_pending_c0 removed (2026-04-24).
    # Old flow waited for C0 bar to CLOSE, ran 3 gates (distance/wick/direction),
    # THEN placed MT5 stop — a 15-min lag that killed most setups before the order
    # was even live. New flow: _scan_c1_rejection builds the stop Signal directly
    # on C1 close. Structural invalidation (main.py._check_stop_invalidation) and
    # time expiry (main.py._expire_pending_stops) govern the lifecycle thereafter.

    # === ENTRY TYPE 2: IMPULSE ===

    def _scan_impulse(self, bar: pd.Series, prev_bar: pd.Series,
                      df: pd.DataFrame, market: MarketState
                      ) -> Optional[Signal]:
        """
        Impulse entry: strong body candle in trending market with volume.
        - Trend must be established (HH/HL or LL/LH)
        - Body ratio >= impulse_min_body_ratio
        - Volume > SMA(20) * multiplier
        - Clean range to the left (no congestion)
        """
        if market.trend == TrendType.CONSOLIDATION:
            logger.debug("Impulse scan: skipping — market in consolidation")
            return None

        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        br = body_ratio(o, c, h, l)
        if br < self.cfg.impulse_min_body_ratio:
            logger.debug("Impulse scan: body_ratio %.2f < min %.2f", br, self.cfg.impulse_min_body_ratio)
            return None

        # Volume check — skip filter when no real volume data (common for gold on TwelveData)
        if "Volume" in df.columns:
            vol = float(bar["Volume"])
            vol_sma = float(df["Volume"].tail(20).mean())
            if vol_sma > 0 and vol > 0 and vol < vol_sma * self.cfg.impulse_volume_multiplier:
                logger.debug("Impulse scan: volume %.0f < SMA*%.1f (%.0f)", vol, self.cfg.impulse_volume_multiplier, vol_sma * self.cfg.impulse_volume_multiplier)
                return None
            vol_ratio = vol / vol_sma if vol_sma > 0 else 1.0
        else:
            vol_ratio = 1.0

        # Clean range check (no congestion to the left)
        lookback = min(self.cfg.impulse_clean_range_lookback, len(df) - 1)
        if not self._has_clean_range(df, lookback, "BUY" if is_bullish(o, c) else "SELL"):
            return None

        # Direction must align with trend
        if market.trend == TrendType.UPTREND and not is_bullish(o, c):
            return None
        if market.trend == TrendType.DOWNTREND and not is_bearish(o, c):
            return None

        # Find nearest S/R for context
        if is_bullish(o, c):
            direction = TradeDirection.BUY
            entry = c  # Enter at close of impulse candle
            sl = l - pips_to_price(5)  # Below impulse candle low
            sr = self.analyzer.get_nearest_support(
                market.support_levels, entry
            )
        else:
            direction = TradeDirection.SELL
            entry = c
            sl = h + pips_to_price(5)
            sr = self.analyzer.get_nearest_resistance(
                market.resistance_levels, entry
            )

        if sr is None:
            # Create a synthetic level
            sr = SRLevel(price=sl, zone_type=ZoneType.SUPPORT if direction == TradeDirection.BUY else ZoneType.RESISTANCE)

        risk_pips = price_to_pips(abs(entry - sl))
        tp1, tp2 = self._calculate_tp(direction, entry, risk_pips, market)

        return Signal(
            trade_id=f"IMP-{uuid.uuid4().hex[:8]}",
            direction=direction,
            entry_type=EntryType.IMPULSE,
            entry_price=entry,
            sl_price=sl,
            tp1_price=tp1,
            tp2_price=tp2,
            risk_pips=risk_pips,
            sr_level=sr,
            context={
                "impulse_body_ratio": br,
                "impulse_volume_ratio": vol_ratio,
                "clean_range_bars": lookback,
                "trend": market.trend.value,
            }
        )

    def _has_clean_range(self, df: pd.DataFrame, lookback: int,
                         direction: str) -> bool:
        """Check if price has clean range (no congestion) to the left."""
        if lookback <= 0 or len(df) < lookback + 1:
            return True

        recent = df.tail(lookback + 1)
        current = recent.iloc[-1]

        if direction == "BUY":
            # For buys, check that current high is above all recent highs
            prev_highs = recent["High"].iloc[:-1]
            return float(current["High"]) > float(prev_highs.max())
        else:
            prev_lows = recent["Low"].iloc[:-1]
            return float(current["Low"]) < float(prev_lows.min())

    # === ENTRY TYPE 3: BREAK & RETEST ===

    def _scan_break_retest(self, bar: pd.Series, df: pd.DataFrame,
                           market: MarketState) -> Optional[Signal]:
        """
        Break & Retest entry (Raja's 80% rule):
        1. Price breaks through S/R level
        2. Pulls back to retest the broken level (now flipped)
        3. C1/C0 rejection at the flipped zone
        """
        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        break_conf_price = pips_to_price(self.cfg.break_confirmation_pips)

        # Check for support break -> becomes resistance (sell setup)
        for level in market.support_levels:
            # Check if recent bars broke below this support
            recent_bars = df.tail(self.cfg.retest_max_bars)
            broke_below = any(
                float(recent_bars["Close"].iloc[i]) < level.price - break_conf_price
                for i in range(max(0, len(recent_bars) - self.cfg.retest_max_bars),
                               len(recent_bars) - 1)
            )

            if broke_below:
                # Now check if current bar is retesting from below
                if abs(h - level.price) <= self.cfg.rejection_tolerance:
                    if is_bearish(o, c):
                        # Bearish rejection at broken support (now resistance)
                        entry = l
                        sl = h + pips_to_price(1)
                        risk_pips = price_to_pips(abs(entry - sl))
                        tp1, tp2 = self._calculate_tp(
                            TradeDirection.SELL, entry, risk_pips, market
                        )

                        flipped = SRLevel(
                            price=level.price,
                            zone_type=ZoneType.RESISTANCE,
                            touches=level.touches,
                            htf_aligned=level.htf_aligned,
                            strength=level.strength,
                        )

                        return Signal(
                            trade_id=f"BR-{uuid.uuid4().hex[:8]}",
                            direction=TradeDirection.SELL,
                            entry_type=EntryType.BREAK_RETEST,
                            entry_price=entry,
                            sl_price=sl,
                            tp1_price=tp1,
                            tp2_price=tp2,
                            risk_pips=risk_pips,
                            sr_level=flipped,
                            context={
                                "break_level_price": level.price,
                                "retest_bars_waited": self.cfg.retest_max_bars,
                                "original_zone_type": "support",
                            }
                        )

        # Check for resistance break -> becomes support (buy setup)
        for level in market.resistance_levels:
            recent_bars = df.tail(self.cfg.retest_max_bars)
            broke_above = any(
                float(recent_bars["Close"].iloc[i]) > level.price + break_conf_price
                for i in range(max(0, len(recent_bars) - self.cfg.retest_max_bars),
                               len(recent_bars) - 1)
            )

            if broke_above:
                if abs(l - level.price) <= self.cfg.rejection_tolerance:
                    if is_bullish(o, c):
                        entry = h
                        sl = l - pips_to_price(1)
                        risk_pips = price_to_pips(abs(entry - sl))
                        tp1, tp2 = self._calculate_tp(
                            TradeDirection.BUY, entry, risk_pips, market
                        )

                        flipped = SRLevel(
                            price=level.price,
                            zone_type=ZoneType.SUPPORT,
                            touches=level.touches,
                            htf_aligned=level.htf_aligned,
                            strength=level.strength,
                        )

                        return Signal(
                            trade_id=f"BR-{uuid.uuid4().hex[:8]}",
                            direction=TradeDirection.BUY,
                            entry_type=EntryType.BREAK_RETEST,
                            entry_price=entry,
                            sl_price=sl,
                            tp1_price=tp1,
                            tp2_price=tp2,
                            risk_pips=risk_pips,
                            sr_level=flipped,
                            context={
                                "break_level_price": level.price,
                                "retest_bars_waited": self.cfg.retest_max_bars,
                                "original_zone_type": "resistance",
                            }
                        )

        return None

    # === PRE-ENTRY FILTERS ===

    def _passes_pre_entry_filters(self, signal: Signal,
                                  market: MarketState,
                                  df: pd.DataFrame) -> bool:
        """
        Raja's pre-entry checklist:
        1. Minimum room to opposing S/R (min_room_pips)
        2. Not in mid-range (max_mid_range_pct)
        3. SL within bounds (min_sl_pips, max_risk_pips)
        4. Spread check
        """
        # Diagnostic — log every signal entering pre-filter pipeline so zero-trade
        # investigations can see which filter dropped it (all reject paths INFO).
        logger.info(
            "Pre-filter CHECK: %s entry=%.2f SL=%.2f risk=%.1fp "
            "(%s zone=%.2f strength=%.1f)",
            signal.direction.value, signal.entry_price, signal.sl_price,
            signal.risk_pips, signal.entry_type.value,
            signal.sr_level.price, signal.sr_level.strength,
        )

        # 1. Room to opposing S/R
        room = self.analyzer.get_room_to_opposing(
            signal.direction.value, signal.entry_price,
            market.support_levels, market.resistance_levels
        )
        if room < self.cfg.min_room_pips:
            logger.info("Pre-filter REJECT: room %.1f pips < min %.1f (entry=%.2f, %s)",
                        room, self.cfg.min_room_pips, signal.entry_price, signal.direction.value)
            return False

        # 2. Mid-range check
        if market.support_levels and market.resistance_levels:
            nearest_sup = max(l.price for l in market.support_levels)
            nearest_res = min(l.price for l in market.resistance_levels)
            total_range = nearest_res - nearest_sup
            if total_range > 0:
                position = (signal.entry_price - nearest_sup) / total_range
                mid_low = 0.5 - self.cfg.max_mid_range_pct / 2
                mid_high = 0.5 + self.cfg.max_mid_range_pct / 2
                if mid_low < position < mid_high:
                    logger.info(
                        "Pre-filter REJECT: mid-range position %.2f "
                        "(band=%.2f-%.2f, entry=%.2f)",
                        position, mid_low, mid_high, signal.entry_price
                    )
                    return False

        # 3. SL bounds - reject signals outside range (no padding)
        if signal.risk_pips < self.cfg.min_sl_pips:
            logger.info(
                "Pre-filter REJECT: SL too tight %.1f pips < min %.1f "
                "(entry=%.2f, %s)",
                signal.risk_pips, self.cfg.min_sl_pips,
                signal.entry_price, signal.direction.value
            )
            return False
        if signal.risk_pips > self.cfg.max_risk_pips:
            logger.info(
                "Pre-filter REJECT: SL too wide %.1f pips > max %.1f "
                "(entry=%.2f, %s)",
                signal.risk_pips, self.cfg.max_risk_pips,
                signal.entry_price, signal.direction.value
            )
            return False

        # 4. HTF alignment + strength filter REMOVED per entry-plan update.
        # Reason: body-touch filter + pivot strength already filter zone quality upstream.
        # The HTF+strength gate was blocking orphan-but-valid zones from reacting.
        # Stop-order entry at C1 extreme provides its own confirmation (price must
        # break the C1 wick to trigger fill), so we no longer need this soft filter.

        logger.info("Pre-filter PASSED: room=%.1f, risk=%.1f pips, sr_str=%.1f, htf=%s",
                     room, signal.risk_pips, signal.sr_level.strength, signal.sr_level.htf_aligned)

        return True

    # === FAKEOUT DETECTION ===

    def _is_fakeout(self, signal: Signal, bar: pd.Series,
                    df: pd.DataFrame, market: MarketState) -> bool:
        """
        Detect potential fakeout signals:
        - Very weak body (< 0.15 body ratio) = doji/indecision
        - Low volume impulse (only when real volume data exists)
        - Counter-trend without strong body AND low volume session
        """
        o, h, l, c = float(bar["Open"]), float(bar["High"]), \
                      float(bar["Low"]), float(bar["Close"])

        br = body_ratio(o, c, h, l)

        # Very weak body = doji/indecision candle (loosened from 0.20 to 0.15)
        if br < 0.15:
            logger.debug("Fakeout: doji/indecision body ratio %.2f", br)
            return True

        # Low volume fakeout — only check when real volume data exists
        # (TwelveData often returns 0 volume for gold, so skip in that case)
        if market.current_volume_level == VolumeLevel.LOW:
            avg_vol = float(df["Volume"].tail(20).mean()) if "Volume" in df.columns else 0
            if avg_vol > 0:  # Only filter when we have real volume data
                if signal.entry_type == EntryType.IMPULSE:
                    logger.debug("Fakeout: impulse with confirmed low volume")
                    return True

        # Counter-trend without strong body: need body_ratio >= 0.35 (loosened from 0.40)
        if signal.direction == TradeDirection.BUY and market.trend == TrendType.DOWNTREND:
            if br < 0.35 and not is_high_volume_session(market.session):
                logger.debug("Fakeout: counter-trend buy without conviction (br=%.2f)", br)
                return True
        if signal.direction == TradeDirection.SELL and market.trend == TrendType.UPTREND:
            if br < 0.35 and not is_high_volume_session(market.session):
                logger.debug("Fakeout: counter-trend sell without conviction (br=%.2f)", br)
                return True

        return False

    # === TP CALCULATION ===

    def _calculate_tp(self, direction: TradeDirection, entry: float,
                      risk_pips: float, market: MarketState
                      ) -> tuple:
        """
        Calculate TP1 and TP2 prices.
        TP1 = max(min_tp1_pips, SL size) — floor of 30 pips, or 1:1 if SL > 30p
        TP2 = nearest opposing S/R or max 2.5R
        """
        risk_dollars = pips_to_price(risk_pips)

        # 🔴 LIVE RISK — TP1: minimum 30 pips, or 1:1 RR if SL >= 30 pips
        min_tp1 = getattr(self.cfg, 'min_tp1_pips', 30.0)
        tp1_pips = max(min_tp1, risk_pips * self.cfg.tp1_rr)
        tp1_dollars = pips_to_price(tp1_pips)

        if direction == TradeDirection.BUY:
            tp1 = entry + tp1_dollars
            # TP2: nearest resistance BEYOND TP1, or max 2.5R fallback
            tp2_max = entry + risk_dollars * self.cfg.tp2_max_rr
            nearest_res = self.analyzer.get_nearest_resistance(
                market.resistance_levels, entry
            )
            # 🔴 LIVE RISK — S/R zone must be FARTHER than TP1 (beyond TP1 in profit
            # direction). Without this guard, a tight S/R just above entry overrides
            # the TP2 max and produces a TP2 that is closer than TP1.
            if nearest_res and nearest_res.price > tp1 and nearest_res.price < tp2_max:
                tp2 = nearest_res.price
                logger.debug("TP2 BUY: using S/R at %.2f (beyond TP1 %.2f, inside 2.5R %.2f)",
                             tp2, tp1, tp2_max)
            else:
                tp2 = tp2_max
                logger.debug("TP2 BUY: using 2.5R max %.2f (no valid S/R beyond TP1)", tp2)
        else:
            tp1 = entry - tp1_dollars
            # TP2: nearest support BEYOND TP1, or max 2.5R fallback
            tp2_max = entry - risk_dollars * self.cfg.tp2_max_rr
            nearest_sup = self.analyzer.get_nearest_support(
                market.support_levels, entry
            )
            # 🔴 LIVE RISK — S/R zone must be FARTHER than TP1 (below TP1 for SELL).
            # Without this guard, the nearest support just below entry (which may be
            # 1-2 price units away) gets used as TP2, producing a worse-than-1:1 trade.
            if nearest_sup and nearest_sup.price < tp1 and nearest_sup.price > tp2_max:
                tp2 = nearest_sup.price
                logger.debug("TP2 SELL: using S/R at %.2f (beyond TP1 %.2f, inside 2.5R %.2f)",
                             tp2, tp1, tp2_max)
            else:
                tp2 = tp2_max
                logger.debug("TP2 SELL: using 2.5R max %.2f (no valid S/R beyond TP1)", tp2)

        return round(tp1, 2), round(tp2, 2)

    def _expire_pending_orders(self):
        """Compatibility shim — strategy no longer holds a pending queue.

        Retained so external callers (main.py session-boundary cleanup) stay safe
        if not yet updated. MT5 pending lifetime is governed by
        main.py._expire_pending_stops() and _check_stop_invalidation().
        """
        if self.pending_orders:
            # Defensive — any stale in-memory state from prior code paths.
            self.pending_orders.clear()
